services:
    email:
        # Build ./docker/email/Dockerfile
        build: ./docker/email
        volumes:
            - ./scripts/email:/scripts
        command: ./scripts/send_email.sh ${EMAIL_RECIPIENT}
