services:
    email:
        # Build ./docker/email/Dockerfile
        build: ./docker/email
        volumes:
            - ./scripts/email:/scripts
        command: ./scripts/send_email.sh ${EMAIL_RECIPIENT}
    db:
        # Build ./docker/db/Dockerfile
        build: ./docker/db
        restart: always
        volumes:
            - dailyreport-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret

    # db admin container for development (http://localhost:8080)
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    dailyreport-mysql-data:
